### PR TITLE
Apply stylua styling

### PR DESCRIPTION
**Pull request by carsakiller**
Applies stylua styling necessary for LLS-Addons

### CODE REVIEW

**Comment by Frityet** [comment]
When I ran stylua on the repo, I got no output and a successful return code, what command did you use to run stylua? I used
```sh
stylua -g "**/*.lua" -- library/yue
```

```sh
stylua library/yue/*.lua
```

**Comment by carsakiller** [comment]
I use the [binary on npm](https://github.com/JohnnyMorganz/StyLua#npm)

**Comment by Frityet** [comment]
> I use the [binary on npm](https://github.com/JohnnyMorganz/StyLua#npm)

I mean like for checking the files, what command did you use after installation

**Comment by carsakiller** [comment]
I ran `npx @johnnymorganz/stylua-bin ./addons/yue/module` in `LLS-Addons` and then pushed it to my fork of your addon.

**Pull request merged**
